"""Initial migration with User and WorkingZone tables

Revision ID: 37b75d3e0369
Revises: 
Create Date: 2025-11-27 11:05:32.332585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b75d3e0369'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_zone',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('x3', sa.Float(), nullable=False),
    sa.Column('y3', sa.Float(), nullable=False),
    sa.Column('x4', sa.Float(), nullable=False),
    sa.Column('y4', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['working_zone.zone_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_global_id', 'user', ['global_id'], unique=False)
    op.create_index('idx_user_zone_id', 'user', ['zone_id'], unique=False)
    op.create_index(op.f('ix_user_global_id'), 'user', ['global_id'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_zone_id'), 'user', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_zone_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_global_id'), table_name='user')
    op.drop_index('idx_user_zone_id', table_name='user')
    op.drop_index('idx_user_global_id', table_name='user')
    op.drop_table('user')
    op.drop_table('working_zone')
    # ### end Alembic commands ###
